### ISSUE TITLE
feature request: allow deployments from mainnet on hardhat in forking mode

### ISSUE THREAD

**Issue by gitpusha** [wighawag/hardhat-deploy-ethers-old#6]
It would be cool if `await ethers.getContract("Bar")`  when run in `hardhat` `forking` mode would let `hardhat-deploy` know that `--network hardhat` can actually also take into consideration the `deployments/` from whatever network is configured in `forking`

**Comment by wighawag** [comment]
That's a good idea, this would have to be implemented in hardhat-deploy
(hardhat-deploy-ethers internally calls `hre.deployments.get`)
